{% set name = "torch-complex" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torch_complex-{{ version }}.tar.gz
  sha256: 8b8ca33634d0c0fd376e0ad2af23f18904d10a0980f10db3fa4db776a6777f0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - torch_complex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kamo-naoyuki/pytorch_complex
  summary: A fugacious python class for PyTorch-ComplexTensor
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
